### ISSUE TITLE
Install problems (folder name)

### ISSUE THREAD

**Issue by CubaLibre84** [akpaevj/Dashboard#1]
First of all, thank you for this nice little plugin!

When installing via git clone, I got an error message that the folder name is not correct (`Dashboard `instead of `dashboard`).
I think this is because your repo name begins with a capital `D`.

Renaming the folder on the server with `mv Dashboard dashboard` fixed it.
BTW: Most of the mature plugins start with `redmine_` as folder name.

**Comment by akpaevj** [comment]
This is true, I know about the problem and I'll fix it in the next release version. Thanks for the issue, I'll describe it in the documentation

**Comment by akpaevj** [comment]
fixed in f21f1d3

**Comment by CubaLibre84** [comment]
Thank you very much for your work! The installation went fine - no issues with the folder name anymore.
However, I needed to run a
` sudo RAILS_ENV=production bundle`
