### ISSUE TITLE
Project selector (drow-down menu or buttons)

### ISSUE THREAD

**Issue by CubaLibre84** [akpaevj/dashboard#11]
In v1.0.6, buttons were introduced to select the project.
(See earlier discussion in #2)

**Issues:**
1.) The projects are not shown up, as the default color is transparent. This is misleading.
2.) There should be an option to set a default color for all projects.
3.) Personally, I don't like the buttons and prefer the drop-down menu. Then it is also possible to visualize projects with their sub-projects

**Comment by CubaLibre84** [comment]
Regarding 1.) As I come from an earlier version, the values were not defined. By saving the setting for the first time, the default color seems to be gray.

**Comment by akpaevj** [comment]
> Regarding 1.) As I come from an earlier version, the values were not defined. By saving the setting for the first time, the default color seems to be gray.

Yes, this is true)

**Comment by akpaevj** [comment]
> In v1.0.6, buttons were introduced to select the project.
> (See earlier discussion in #2)
> 
> **Issues:**
> 1.) The projects are not shown up, as the default color is transparent. This is misleading.
> 2.) There should be an option to set a default color for all projects.
> 3.) Personally, I don't like the buttons and prefer the drop-down menu. Then it is also possible to visualize projects with their sub-projects

1. I know about this problem and fix it in next releases.
2. The same as in the first item
3. I don't use sub-projects, so I didn't check a working with them. But I will release a possibility to work with them. 

Regarding drop-down menu, I'll think what I can do with it

**Comment by akpaevj** [comment]
> Actually, the buttons are nice! However, I have currently 10+ projects open and the top line looks like this:
> It is very crowded, as projects and their subprojects are all displayed.
> ![grafik](https://user-images.githubusercontent.com/10250388/118823280-28543580-b8b9-11eb-8a88-bbb275b3d8b1.png)
> 
> Please also check with the purplemine2 theme. The buttons are here even bigger.
> https://github.com/mrliptontea/PurpleMine2

I use purplemine2 theme too, but it seems not last version , so it works well)) I'll check this in new version and fix if it needs

**Comment by CubaLibre84** [comment]
It is really hard to tell, what is the best arrangement for buttons that also visualize sub-projects.
My first idea is, to not show the buttons for projects, which are sub-projects. If a parent project is selected, the buttons of sub-projects could be displayed (added dynamically). I don't know if this is worth the effort.

**Comment by akpaevj** [comment]
In your case it's really convenient to use drop-down menu instead of badges

**Comment by akpaevj** [comment]
I'll do it customizable and I hope the plugin make your life easily)

**Comment by akpaevj** [comment]
> Actually, the buttons are nice! However, I have currently 10+ projects open and the top line looks like this:
> It is very crowded, as projects and their subprojects are all displayed.
> ![grafik](https://user-images.githubusercontent.com/10250388/118823280-28543580-b8b9-11eb-8a88-bbb275b3d8b1.png)
> 
> Please also check with the purplemine2 theme. The buttons are here even bigger.
> https://github.com/mrliptontea/PurpleMine2

I check the theme last version and couldn't reproduce the problem. Could you show me a screenshot of Chrome dev console, I want to see CSS layers of the div block
![image](https://user-images.githubusercontent.com/40080662/118828246-c3eba300-b8c5-11eb-9729-8b03a0f8ae27.png)

**Comment by akpaevj** [comment]
> Actually, the buttons are nice! However, I have currently 10+ projects open and the top line looks like this:
> It is very crowded, as projects and their subprojects are all displayed.
> ![grafik](https://user-images.githubusercontent.com/10250388/118823280-28543580-b8b9-11eb-8a88-bbb275b3d8b1.png)
> 
> Please also check with the purplemine2 theme. The buttons are here even bigger.
> https://github.com/mrliptontea/PurpleMine2

Fixed it. It was a problem of CSS styling

**Comment by CubaLibre84** [comment]
In 1.0.10 the button radius scales with the badge height. If the project names fill up three lines, this looks odd:

![grafik](https://user-images.githubusercontent.com/10250388/119499816-65ac3d80-bd67-11eb-9196-3273e02fb791.png)
![grafik](https://user-images.githubusercontent.com/10250388/119502450-3ba84a80-bd6a-11eb-842f-0321807f656f.png)

**Comment by akpaevj** [comment]
I've checked it in current version. Try use ctrl + f5, maybe your browser cached css
