### ISSUE TITLE
Only show project badge if ALL projects are selected

### ISSUE THREAD

**Issue by CubaLibre84** [akpaevj/dashboard#12]
When selecting a project, the project badge (top right corner of each ticket) is the same.
As it is redundant, it is not needed to be displayed. Omitting it will lead to a cleaner layout.

**Comment by akpaevj** [comment]
I agree with you. Fix it in the next release

**Comment by CubaLibre84** [comment]
First of all, thanks for your work again!
I observed, that if the dropdown list is used as a project selector, the badges are still shown...

**Comment by akpaevj** [comment]
> First of all, thanks for your work again!
> I observed, that if the dropdown list is used as a project selector, the badges are still shown...

This is true. If "Display child projects tasks" flag is set, than it always shows badges.

**Comment by akpaevj** [comment]
In the next version I'll try to fix this behaviour
