### ISSUE TITLE
Show tickets of sub-projects in top-project dashboard

### ISSUE THREAD

**Issue by CubaLibre84** [akpaevj/dashboard#13]
In a top-project / sub-project hierarchy, the "sub-tickets" are not shown in a top-project dashboard.
However, there are use cases, when this is needed and others where it is not.
Consequently, a UI checkbox ("show tickets of sub projects") could be added.

**Comment by akpaevj** [comment]
Honestly I didn't want to overcharge dashboard main page and can create a global plugin setting to show or hide sub-tasks for projects

**Comment by akpaevj** [comment]
Do you mean the function doesn't work in general or just there are no the same function on the main page of the dashboard?

**Comment by CubaLibre84** [comment]
I check further: The function does not work in general, independent of the project selector style.

**Comment by akpaevj** [comment]
Honestly I couldn't reproduce the problem(
![image](https://user-images.githubusercontent.com/40080662/119503590-cfcadf80-bd73-11eb-9172-db1782f0cf6b.png)

**Comment by akpaevj** [comment]
This problem has been resolved in 1.0.11 version (latest)
