### ISSUE TITLE
Links do not work

### ISSUE THREAD

**Issue by CubaLibre84** [akpaevj/dashboard#2]
In the Dashboard, all links do not work:
e.g.
`http://172.16.32.41/redmine/dashboard/issues/12`.
--> Page not found

Furthermore, globally **all** issues are shown here and not for only one selected project.
I thought, the dashboard is added not in the top menu (Main Page/Projects/Help) but in the project tabs (Tickets Gantt, Calendar, Wiki...).
Is this intended?

**Comment by akpaevj** [comment]
It seems to me I've found out what's wrong) I set the plugin index page as a root page of my instance of the Redmine application, so when I click on the issue card my relative Uri doesn't contain "/dashboard/" part and works well. It's really a problem and I'll fix it.  Regarding your second question, this is really intended, I planned to add in the top of the board a "select" field, where user can choose a project that he wants to watch. Also feel free to ask any questions and say any suggestions)

**Comment by CubaLibre84** [comment]
Thank you for your work! I can see the project select field now.

However, the links still do now work, as they still contain a `dashboard\` in the URL.
If I remove that part from the URL manually, the links do work.

I think a have a "normal" setup without any other special settings involved. I don't know how I can help you to reproduce that on your machine. Tested with v1.0.5

**Comment by akpaevj** [comment]
Could you write your application base URI here?

**Comment by CubaLibre84** [comment]
I recently activated a company internal subdomain. The URL I receive from the dashboard is:
`http://redmine.eltroplan.com/dashboard/issues/1`

We are using Redmin 4.2

**Comment by CubaLibre84** [comment]
I cleared the cache and ran a `sudo systemctl restart apache2`.  Still the same issue  :-/

**Comment by akpaevj** [comment]
> I cleared the cache and ran a `sudo systemctl restart apache2`. Still the same issue :-/

Event after switching to the new version (1.0.6)?

**Comment by CubaLibre84** [comment]
Oh sorry. I just tried v1.0.6 and now the links do work.  Good job!

Is it correct, that the dropdown list is now **just a simple button**?
![grafik](https://user-images.githubusercontent.com/10250388/118818372-8c282f80-b8b4-11eb-9164-55adca723681.png)

**Comment by akpaevj** [comment]
It's correct. if there are several projects, they will look like this
![image](https://user-images.githubusercontent.com/40080662/118819108-b0d4d500-b8bd-11eb-9bc6-6dc38dbe88d4.png)

**Comment by akpaevj** [comment]
Alose you should to set projects and statuses colors in plugin settings, cause they are not displayed correctly on your screenshots. You can see how it looks in the repository's Readme.md
