### ISSUE TITLE
Cannot find routes.rb file to configure the homepage as dashboard

### ISSUE THREAD

**Issue by ihmcjacky** [akpaevj/dashboard#21]
![image](https://user-images.githubusercontent.com/6357898/120533690-977e6d80-c413-11eb-8438-e8ff75e56098.png)

Sorry if I find a wrong place to ask, my redmine version is 4.1.1
![image](https://user-images.githubusercontent.com/6357898/120533865-c7c60c00-c413-11eb-9bbd-78b3c6da2252.png)

However I can't find the config/routes.rb to set the default homepage of the dashboard, please kindly advice, thank you for the help

**Comment by akpaevj** [comment]
It seems you try to find this file in plugin directory. You can reach it by path %REDMINE_FOLDER%/config/routes.rb

**Comment by ihmcjacky** [comment]
> It seems you try to find this file in the plugin directory, but this is wrong way. You can reach it by path %REDMINE_FOLDER%/config/routes.rb

Thanks for the reply, I try to navigate to redmine folder, it only has a conf folder in redmine folder, and in the conf folder it just contains 2 yaml files  
![image](https://user-images.githubusercontent.com/6357898/120580859-70985980-c45c-11eb-93c9-6122f4096507.png)
![image](https://user-images.githubusercontent.com/6357898/120580769-51013100-c45c-11eb-9442-a639f9bc190d.png)

**Comment by akpaevj** [comment]
You use Bitnami. Try to find config files by path /opt/bitnami/apps/redmine/htdocs or something similar

**Comment by ihmcjacky** [comment]
> You use Bitnami. Try to find config files by path /opt/bitnami/apps/redmine/htdocs or something similar

Thanks so much!! I just find it with find cmd, appreciate for the help, cheers
