### ISSUE TITLE
Dashboard crashing 500

### ISSUE THREAD

**Issue by hermannkm** [akpaevj/dashboard#22]
**Error**
Plugin configuration works, when clicking on Dashboard menu (top left) I get "Internal Error".

**Logfile**

Started GET "/dashboard" for 91.141.1.130 at 2021-06-05 07:45:00 +0200
Processing by DashboardController#index as HTML
  Current user: admin (id=1)
Completed 500 Internal Server Error in 86ms (ActiveRecord: 14.5ms)

ArgumentError (comparison of Date with nil failed):

plugins/dashboard/app/controllers/dashboard_controller.rb:99:in `sort_by'
plugins/dashboard/app/controllers/dashboard_controller.rb:99:in `get_issues'
plugins/dashboard/app/controllers/dashboard_controller.rb:13:in `index'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Desktop**
macOS 11.4, Safari 14.1.1

**Redmine**
  Redmine version                4.2.1.stable.21007
  Ruby version                   2.7.2-p137 (2020-10-01) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
SCM:
  Subversion                     1.13.0
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  dashboard                      1.0.11
  redhopper                      2.0.0
  redmine_agile                  1.6.1
  redmine_checklists             3.1.19
  redmine_drawio                 1.0.3
  redmine_ics_export             4.0.1.dev
  redmine_lightbox2              0.5.1
  redmine_my_page                0.1.13
  redmine_preview_inline         1.0.3
  scrum                          0.21.0

installed on 

Linux redmine.klocker-mark.eu 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 20.04)

**Comment by hermannkm** [comment]
Knowing that some of my items have no dates inserted (yet) I tried changing

```
#        :created_at => item.start_date,
        :created_at => item.start_date.nil? ? Date.today : item.start_date, 

```
at line 94 in dashboard_controller.rb got it running, but don't know if this is as it should be.

**Comment by akpaevj** [comment]
I think it's exactly what's went wrong. Thank you for the issue, I'll fix it nearest time
