### ISSUE TITLE
Missing links when in shared domain Redmine installation

### ISSUE THREAD

**Issue by Tony2987** [akpaevj/dashboard#31]
Clean install of Redmine in a shared domain enviroment (i.e. domain.com/redmine), with MariaDB and Apache.
Dashboard is detected by Redmine, but on main Redmine page top changes to "translation missing: en.top_menu_item_title", returns "Page not found" when clicked, and plugins settings page (domain.com/redmine/settings/plugin/dashboard) also results in a 404.

No other services installed in the machine besides the minimum required by Redmine, no other plugins installed in Redmine.

**Comment by akpaevj** [comment]
Could you tell me, what version of Redmine do you use?

**Comment by Tony2987** [comment]
Redmine 4.0.7-1. Also, Debian Linux.
I figured out the issue. Git clone resulted in acquiring a folder called "Dashboard", but Linux is case sensitive. Renaming to "dashboard" fixed.

**Comment by akpaevj** [comment]
This problem showed itself in #1. This is why I've already renamed this repository from "Dashboard" to "dashboard")
