### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by joho1968** [akpaevj/dashboard#34]
sv:
  top_menu_item_title: "Dashboard"
  settings_header_statuses: "Statusfärger"
  settings_header_projects: "Projektfärger"
  settings_header_other: "Övrigt"
  settings_use_drop_down_menu: 'Använd drop-down-meny för att välja projekt'
  settings_display_closed_statuses: 'Visa "stängda"'
  settings_display_child_projects_tasks: 'Visa underprojekts uppgifter'
  settings_display_minimized_closed_issue_cards: 'Visa "stängda" kort minimerade'
  settings_enable_drag_and_drop: '"Drag-och-Släpp" status-hantering'
  settings_generate_colors: "Skapa färger"
  executor_not_set: "Inte konfigurerat"
  label_all: "Alla"

**Comment by akpaevj** [comment]
Added
