### ISSUE TITLE
fr.yml

### ISSUE THREAD

**Issue by Timothy-Anders0n** [akpaevj/dashboard#49]
Good afternoon,

here joined, the locale file for the French translation of dashboard (zipped as the file dialog filter does not allow .yml files).

Thanks for your work, it's greatly appreciated.

-Tim.

[fr.yml.zip](https://github.com/akpaevj/dashboard/files/11478653/fr.yml.zip)

**Comment by akpaevj** [comment]
Added

**Comment by akpaevj** [comment]
Added
